### PR TITLE
fix issue #30

### PR DESCRIPTION
**Pull request by ashirman**
hi, please take a loot a fix for issue #30 . The summary of changes is following: 
1. add message id param for replaceResultMessage template.
2. initialize  message id by current time in millisecond if no explicit value passed from user call.
3. add API for explicit message id definition.

### CODE REVIEW

**Comment by ashirman** [comment]
@pfgray hello, would you please take a look my merge request and give your :+1:  or :-1: ? also it would be great if you could clarify the release schedule. thanks.

**Comment by pfgray** [comment]
This looks good, and also solves #27. I'd like to merge this, however you'll need to sign a contributer's agreement before I am allowed to. Please contact @LMattson for details on how to do that.

As far as release schedule, there is none. I usually just push a new version whenever we get a fix.

**Comment by Prasannaa-P** [comment]
@pfgray , May I know when this fix will get merged and release?

**Comment by Prasannaa-P** [comment]
@LMattson / @pfgray / @ashirman 
Would like to know what it takes to get this PR merged and released.

**Comment by pfgray** [comment]
This issue was fixed in `1.2.0` in another PR

**Pull request closed without merging**
