### PR TITLE
update replaceResult with messageIdentifier - fix for issue#27

### PR DESCRIPTION
**Pull request by ganeshmaligithub**
- add imsx_messageIdentifier as part of replaceResult
- add language en along with resultScore textString

### CODE REVIEW

**Comment by ganeshmaligithub** [comment]
@pfgray would request to take a look at this PR, it has fix for #27

**Comment by pfgray** [comment]
Hi @ganeshmaligithub, thanks for your contribution, it looks good 👍 

I made a slight modification for backwards compatibility, and created a PR against your fork [here](https://github.com/ganeshmaligithub/basiclti-util-java/pull/1). Could you take a look at that PR? I'd like to merge this, but don't want to introduce breaking changes if we can help it.

thanks!

**Comment by pfgray** [comment]
@ganeshmaligithub, I'll release a new version after this PR get merged

**Comment by ganeshmaligithub** [comment]
@pfgray, the new PR (backwards compatibility) looks good and I have merged it.

**Comment by pfgray** [comment]
@ganeshmaligithub, looks good, thanks for your contribution!

**Pull request merged**
