### PR TITLE
POXRequest replaceResult: oauth_body_hash

### LINKED ISSUE #3: POX replaceResult: oauth_body_hash
Sakai is rejecting replaceResult calls with "Did not find oauth_body_hash". Moodle requires it as well ( https://github.com/moodle/moodle/blob/master/mod/lti/OAuthBody.php ).

I have a WIP commit up at https://github.com/bluej100/basiclti-util-java/commit/9d6d9652655c44b2bd8425db6ce60f9cf9bf1e17#diff-d41d8cd98f00b204e9800998ecf8427e , but it breaks signing.

### PR DESCRIPTION
**Pull request by bluej100**
I believe this fixes #3. I've tested against Canvas and Sakai. I apologize for the long delay.

I did a little refactoring here to make testing easier. I tried to keep the diff small.

### CODE REVIEW

**Comment by pfgray** [comment]
Thanks so much for doing this, @bluej100, I really appreciate all of your work!

**Comment by bluej100** [comment]
The least I can do, fixing the bug I added. I really appreciate your maintaining this.

**Comment by bluej100** [comment]
Would you like me to deploy this to the Maven repository, or is there anything currently in flux?

**Comment by pfgray** [comment]
No, that would be perfect, thanks. Just bump the patch number

**Comment by bluej100** [comment]
(I hope I understood correctly that you meant bump the version to 1.1.1.)

**Comment by pfgray** [comment]
Yup!

**Comment by bluej100** [comment]
I think it's done? I'm getting strangely small release jars in my target directory.

https://oss.sonatype.org/content/groups/public/org/imsglobal/basiclti-util/1.1.1/

**Comment by bluej100** [comment]
Fixed. Sorry about that.

https://oss.sonatype.org/content/groups/public/org/imsglobal/basiclti-util/1.1.1/

**Comment by bluej100** [comment]
For our future reference:

  mvn install
  mvn source:jar
  mvn javadoc:jar
  cd target
  cp ../pom.xml .
  gpg -ab basiclti-util-1.1.1.jar
  gpg -ab basiclti-util-1.1.1-javadoc.jar
  gpg -ab basiclti-util-1.1.1-sources.jar
  gpg -ab pom.xml
  jar -cvf bundle.jar basiclti-util-1.1.1.jar basiclti-util-1.1.1.jar.asc pom.xml pom.xml.asc basiclti-util-1.1.1-javadoc.jar basiclti-util-1.1.1-javadoc.jar.asc

Log into https://oss.sonatype.org/#stagingRepositories with your credentials from their JIRA, click on Staging Upload, upload bundle.jar as an Artifact Bundle. Next, click on Staging Repositories, find your repository, verify that its contents are correct, and click Release.

**Comment by bluej100** [comment]
The new artifacts have been synced to http://repo.maven.apache.org/maven2/org/imsglobal/basiclti-util/1.1.1/ , and I've confirmed them with my local project.

**Pull request merged**
